// @generated by protoc-gen-es v2.2.5 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file voiceAgent/proto/messages.proto (package voice_agent, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file voiceAgent/proto/messages.proto.
 */
export declare const file_voiceAgent_proto_messages: GenFile;

/**
 * @generated from message voice_agent.InputAudio
 */
export declare type InputAudio = Message<"voice_agent.InputAudio"> & {
  /**
   * @generated from field: bytes audio_data = 1;
   */
  audioData: Uint8Array;

  /**
   * @generated from field: voice_agent.InputAudio.AudioEncoding encoding = 2;
   */
  encoding: InputAudio_AudioEncoding;

  /**
   * @generated from field: int32 sample_rate_hertz = 3;
   */
  sampleRateHertz: number;
};

/**
 * Describes the message voice_agent.InputAudio.
 * Use `create(InputAudioSchema)` to create a new message.
 */
export declare const InputAudioSchema: GenMessage<InputAudio>;

/**
 * @generated from enum voice_agent.InputAudio.AudioEncoding
 */
export enum InputAudio_AudioEncoding {
  /**
   * @generated from enum value: UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: LINEAR_16 = 1;
   */
  LINEAR_16 = 1,

  /**
   * @generated from enum value: FLAC = 2;
   */
  FLAC = 2,

  /**
   * @generated from enum value: MULAW = 3;
   */
  MULAW = 3,

  /**
   * @generated from enum value: AMR = 4;
   */
  AMR = 4,

  /**
   * @generated from enum value: AMR_WB = 5;
   */
  AMR_WB = 5,

  /**
   * @generated from enum value: OGG_OPUS = 6;
   */
  OGG_OPUS = 6,

  /**
   * @generated from enum value: SPEEX_WITH_HEADER_BYTE = 7;
   */
  SPEEX_WITH_HEADER_BYTE = 7,

  /**
   * @generated from enum value: ALAW = 8;
   */
  ALAW = 8,
}

/**
 * Describes the enum voice_agent.InputAudio.AudioEncoding.
 */
export declare const InputAudio_AudioEncodingSchema: GenEnum<InputAudio_AudioEncoding>;

/**
 * @generated from message voice_agent.OutputAudio
 */
export declare type OutputAudio = Message<"voice_agent.OutputAudio"> & {
  /**
   * @generated from field: bytes audio_data = 1;
   */
  audioData: Uint8Array;

  /**
   * @generated from field: voice_agent.OutputAudio.OutputAudioEncoding encoding = 2;
   */
  encoding: OutputAudio_OutputAudioEncoding;
};

/**
 * Describes the message voice_agent.OutputAudio.
 * Use `create(OutputAudioSchema)` to create a new message.
 */
export declare const OutputAudioSchema: GenMessage<OutputAudio>;

/**
 * @generated from enum voice_agent.OutputAudio.OutputAudioEncoding
 */
export enum OutputAudio_OutputAudioEncoding {
  /**
   * @generated from enum value: UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: LINEAR_16 = 1;
   */
  LINEAR_16 = 1,

  /**
   * @generated from enum value: MP3 = 2;
   */
  MP3 = 2,

  /**
   * @generated from enum value: MP3_64_KBPS = 4;
   */
  MP3_64_KBPS = 4,

  /**
   * @generated from enum value: OGG_OPUS = 3;
   */
  OGG_OPUS = 3,

  /**
   * @generated from enum value: MULAW = 5;
   */
  MULAW = 5,

  /**
   * @generated from enum value: ALAW = 6;
   */
  ALAW = 6,
}

/**
 * Describes the enum voice_agent.OutputAudio.OutputAudioEncoding.
 */
export declare const OutputAudio_OutputAudioEncodingSchema: GenEnum<OutputAudio_OutputAudioEncoding>;

/**
 * @generated from message voice_agent.Interaction
 */
export declare type Interaction = Message<"voice_agent.Interaction"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string text = 2;
   */
  text: string;

  /**
   * @generated from oneof voice_agent.Interaction.Audio
   */
  Audio: {
    /**
     * @generated from field: voice_agent.InputAudio input = 3;
     */
    value: InputAudio;
    case: "input";
  } | {
    /**
     * @generated from field: voice_agent.OutputAudio output = 4;
     */
    value: OutputAudio;
    case: "output";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from field: string LanguageCode = 5;
   */
  LanguageCode: string;
};

/**
 * Describes the message voice_agent.Interaction.
 * Use `create(InteractionSchema)` to create a new message.
 */
export declare const InteractionSchema: GenMessage<Interaction>;

