// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.1
// source: voiceAgent/proto/messages.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InputAudio_AudioEncoding int32

const (
	InputAudio_UNSPECIFIED            InputAudio_AudioEncoding = 0
	InputAudio_LINEAR_16              InputAudio_AudioEncoding = 1
	InputAudio_FLAC                   InputAudio_AudioEncoding = 2
	InputAudio_MULAW                  InputAudio_AudioEncoding = 3
	InputAudio_AMR                    InputAudio_AudioEncoding = 4
	InputAudio_AMR_WB                 InputAudio_AudioEncoding = 5
	InputAudio_OGG_OPUS               InputAudio_AudioEncoding = 6
	InputAudio_SPEEX_WITH_HEADER_BYTE InputAudio_AudioEncoding = 7
	InputAudio_ALAW                   InputAudio_AudioEncoding = 8
)

// Enum value maps for InputAudio_AudioEncoding.
var (
	InputAudio_AudioEncoding_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "LINEAR_16",
		2: "FLAC",
		3: "MULAW",
		4: "AMR",
		5: "AMR_WB",
		6: "OGG_OPUS",
		7: "SPEEX_WITH_HEADER_BYTE",
		8: "ALAW",
	}
	InputAudio_AudioEncoding_value = map[string]int32{
		"UNSPECIFIED":            0,
		"LINEAR_16":              1,
		"FLAC":                   2,
		"MULAW":                  3,
		"AMR":                    4,
		"AMR_WB":                 5,
		"OGG_OPUS":               6,
		"SPEEX_WITH_HEADER_BYTE": 7,
		"ALAW":                   8,
	}
)

func (x InputAudio_AudioEncoding) Enum() *InputAudio_AudioEncoding {
	p := new(InputAudio_AudioEncoding)
	*p = x
	return p
}

func (x InputAudio_AudioEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InputAudio_AudioEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_voiceAgent_proto_messages_proto_enumTypes[0].Descriptor()
}

func (InputAudio_AudioEncoding) Type() protoreflect.EnumType {
	return &file_voiceAgent_proto_messages_proto_enumTypes[0]
}

func (x InputAudio_AudioEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InputAudio_AudioEncoding.Descriptor instead.
func (InputAudio_AudioEncoding) EnumDescriptor() ([]byte, []int) {
	return file_voiceAgent_proto_messages_proto_rawDescGZIP(), []int{0, 0}
}

type OutputAudio_OutputAudioEncoding int32

const (
	OutputAudio_UNSPECIFIED OutputAudio_OutputAudioEncoding = 0
	OutputAudio_LINEAR_16   OutputAudio_OutputAudioEncoding = 1
	OutputAudio_MP3         OutputAudio_OutputAudioEncoding = 2
	OutputAudio_MP3_64_KBPS OutputAudio_OutputAudioEncoding = 4
	OutputAudio_OGG_OPUS    OutputAudio_OutputAudioEncoding = 3
	OutputAudio_MULAW       OutputAudio_OutputAudioEncoding = 5
	OutputAudio_ALAW        OutputAudio_OutputAudioEncoding = 6
)

// Enum value maps for OutputAudio_OutputAudioEncoding.
var (
	OutputAudio_OutputAudioEncoding_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "LINEAR_16",
		2: "MP3",
		4: "MP3_64_KBPS",
		3: "OGG_OPUS",
		5: "MULAW",
		6: "ALAW",
	}
	OutputAudio_OutputAudioEncoding_value = map[string]int32{
		"UNSPECIFIED": 0,
		"LINEAR_16":   1,
		"MP3":         2,
		"MP3_64_KBPS": 4,
		"OGG_OPUS":    3,
		"MULAW":       5,
		"ALAW":        6,
	}
)

func (x OutputAudio_OutputAudioEncoding) Enum() *OutputAudio_OutputAudioEncoding {
	p := new(OutputAudio_OutputAudioEncoding)
	*p = x
	return p
}

func (x OutputAudio_OutputAudioEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputAudio_OutputAudioEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_voiceAgent_proto_messages_proto_enumTypes[1].Descriptor()
}

func (OutputAudio_OutputAudioEncoding) Type() protoreflect.EnumType {
	return &file_voiceAgent_proto_messages_proto_enumTypes[1]
}

func (x OutputAudio_OutputAudioEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputAudio_OutputAudioEncoding.Descriptor instead.
func (OutputAudio_OutputAudioEncoding) EnumDescriptor() ([]byte, []int) {
	return file_voiceAgent_proto_messages_proto_rawDescGZIP(), []int{1, 0}
}

type InputAudio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AudioData       []byte                   `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	Encoding        InputAudio_AudioEncoding `protobuf:"varint,2,opt,name=encoding,proto3,enum=voice_agent.InputAudio_AudioEncoding" json:"encoding,omitempty"`
	SampleRateHertz int32                    `protobuf:"varint,3,opt,name=sample_rate_hertz,json=sampleRateHertz,proto3" json:"sample_rate_hertz,omitempty"`
}

func (x *InputAudio) Reset() {
	*x = InputAudio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voiceAgent_proto_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputAudio) ProtoMessage() {}

func (x *InputAudio) ProtoReflect() protoreflect.Message {
	mi := &file_voiceAgent_proto_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputAudio.ProtoReflect.Descriptor instead.
func (*InputAudio) Descriptor() ([]byte, []int) {
	return file_voiceAgent_proto_messages_proto_rawDescGZIP(), []int{0}
}

func (x *InputAudio) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *InputAudio) GetEncoding() InputAudio_AudioEncoding {
	if x != nil {
		return x.Encoding
	}
	return InputAudio_UNSPECIFIED
}

func (x *InputAudio) GetSampleRateHertz() int32 {
	if x != nil {
		return x.SampleRateHertz
	}
	return 0
}

type OutputAudio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AudioData []byte                          `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	Encoding  OutputAudio_OutputAudioEncoding `protobuf:"varint,2,opt,name=encoding,proto3,enum=voice_agent.OutputAudio_OutputAudioEncoding" json:"encoding,omitempty"`
}

func (x *OutputAudio) Reset() {
	*x = OutputAudio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voiceAgent_proto_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutputAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputAudio) ProtoMessage() {}

func (x *OutputAudio) ProtoReflect() protoreflect.Message {
	mi := &file_voiceAgent_proto_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputAudio.ProtoReflect.Descriptor instead.
func (*OutputAudio) Descriptor() ([]byte, []int) {
	return file_voiceAgent_proto_messages_proto_rawDescGZIP(), []int{1}
}

func (x *OutputAudio) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *OutputAudio) GetEncoding() OutputAudio_OutputAudioEncoding {
	if x != nil {
		return x.Encoding
	}
	return OutputAudio_UNSPECIFIED
}

type Interaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Text      string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	IsPartial bool   `protobuf:"varint,7,opt,name=isPartial,proto3" json:"isPartial,omitempty"`
	// Types that are assignable to Audio:
	//
	//	*Interaction_Input
	//	*Interaction_Output
	Audio          isInteraction_Audio `protobuf_oneof:"Audio"`
	LanugageCode   string              `protobuf:"bytes,5,opt,name=lanugage_code,json=lanugageCode,proto3" json:"lanugage_code,omitempty"`
	RecognizedText string              `protobuf:"bytes,6,opt,name=recognized_text,json=recognizedText,proto3" json:"recognized_text,omitempty"`
}

func (x *Interaction) Reset() {
	*x = Interaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voiceAgent_proto_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Interaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interaction) ProtoMessage() {}

func (x *Interaction) ProtoReflect() protoreflect.Message {
	mi := &file_voiceAgent_proto_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interaction.ProtoReflect.Descriptor instead.
func (*Interaction) Descriptor() ([]byte, []int) {
	return file_voiceAgent_proto_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Interaction) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Interaction) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Interaction) GetIsPartial() bool {
	if x != nil {
		return x.IsPartial
	}
	return false
}

func (m *Interaction) GetAudio() isInteraction_Audio {
	if m != nil {
		return m.Audio
	}
	return nil
}

func (x *Interaction) GetInput() *InputAudio {
	if x, ok := x.GetAudio().(*Interaction_Input); ok {
		return x.Input
	}
	return nil
}

func (x *Interaction) GetOutput() *OutputAudio {
	if x, ok := x.GetAudio().(*Interaction_Output); ok {
		return x.Output
	}
	return nil
}

func (x *Interaction) GetLanugageCode() string {
	if x != nil {
		return x.LanugageCode
	}
	return ""
}

func (x *Interaction) GetRecognizedText() string {
	if x != nil {
		return x.RecognizedText
	}
	return ""
}

type isInteraction_Audio interface {
	isInteraction_Audio()
}

type Interaction_Input struct {
	Input *InputAudio `protobuf:"bytes,3,opt,name=input,proto3,oneof"`
}

type Interaction_Output struct {
	Output *OutputAudio `protobuf:"bytes,4,opt,name=output,proto3,oneof"`
}

func (*Interaction_Input) isInteraction_Audio() {}

func (*Interaction_Output) isInteraction_Audio() {}

var File_voiceAgent_proto_messages_proto protoreflect.FileDescriptor

var file_voiceAgent_proto_messages_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x22, 0xaa,
	0x02, 0x0a, 0x0a, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x1d, 0x0a,
	0x0a, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x12, 0x41, 0x0a, 0x08,
	0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25,
	0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x45, 0x6e, 0x63,
	0x6f, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x12,
	0x2a, 0x0a, 0x11, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x68,
	0x65, 0x72, 0x74, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x73, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x48, 0x65, 0x72, 0x74, 0x7a, 0x22, 0x8d, 0x01, 0x0a, 0x0d,
	0x41, 0x75, 0x64, 0x69, 0x6f, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x0f, 0x0a,
	0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d,
	0x0a, 0x09, 0x4c, 0x49, 0x4e, 0x45, 0x41, 0x52, 0x5f, 0x31, 0x36, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x46, 0x4c, 0x41, 0x43, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x55, 0x4c, 0x41, 0x57,
	0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4d, 0x52, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x41,
	0x4d, 0x52, 0x5f, 0x57, 0x42, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x47, 0x47, 0x5f, 0x4f,
	0x50, 0x55, 0x53, 0x10, 0x06, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x50, 0x45, 0x45, 0x58, 0x5f, 0x57,
	0x49, 0x54, 0x48, 0x5f, 0x48, 0x45, 0x41, 0x44, 0x45, 0x52, 0x5f, 0x42, 0x59, 0x54, 0x45, 0x10,
	0x07, 0x12, 0x08, 0x0a, 0x04, 0x41, 0x4c, 0x41, 0x57, 0x10, 0x08, 0x22, 0xea, 0x01, 0x0a, 0x0b,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x61,
	0x75, 0x64, 0x69, 0x6f, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x12, 0x48, 0x0a, 0x08, 0x65, 0x6e,
	0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x76,
	0x6f, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x41, 0x75, 0x64,
	0x69, 0x6f, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x65, 0x6e, 0x63, 0x6f,
	0x64, 0x69, 0x6e, 0x67, 0x22, 0x72, 0x0a, 0x13, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x41, 0x75,
	0x64, 0x69, 0x6f, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x0f, 0x0a, 0x0b, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x4c, 0x49, 0x4e, 0x45, 0x41, 0x52, 0x5f, 0x31, 0x36, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x4d,
	0x50, 0x33, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x50, 0x33, 0x5f, 0x36, 0x34, 0x5f, 0x4b,
	0x42, 0x50, 0x53, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x47, 0x47, 0x5f, 0x4f, 0x50, 0x55,
	0x53, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x55, 0x4c, 0x41, 0x57, 0x10, 0x05, 0x12, 0x08,
	0x0a, 0x04, 0x41, 0x4c, 0x41, 0x57, 0x10, 0x06, 0x22, 0x9a, 0x02, 0x0a, 0x0b, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x69,
	0x73, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x69, 0x73, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x2f, 0x0a, 0x05, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65,
	0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x41, 0x75, 0x64, 0x69,
	0x6f, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x32, 0x0a, 0x06, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x76, 0x6f, 0x69,
	0x63, 0x65, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x41,
	0x75, 0x64, 0x69, 0x6f, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x23,
	0x0a, 0x0d, 0x6c, 0x61, 0x6e, 0x75, 0x67, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x61, 0x6e, 0x75, 0x67, 0x61, 0x67, 0x65, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65,
	0x64, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65,
	0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65, 0x64, 0x54, 0x65, 0x78, 0x74, 0x42, 0x07, 0x0a, 0x05,
	0x41, 0x75, 0x64, 0x69, 0x6f, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x4c, 0x2f, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_voiceAgent_proto_messages_proto_rawDescOnce sync.Once
	file_voiceAgent_proto_messages_proto_rawDescData = file_voiceAgent_proto_messages_proto_rawDesc
)

func file_voiceAgent_proto_messages_proto_rawDescGZIP() []byte {
	file_voiceAgent_proto_messages_proto_rawDescOnce.Do(func() {
		file_voiceAgent_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_voiceAgent_proto_messages_proto_rawDescData)
	})
	return file_voiceAgent_proto_messages_proto_rawDescData
}

var file_voiceAgent_proto_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_voiceAgent_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_voiceAgent_proto_messages_proto_goTypes = []interface{}{
	(InputAudio_AudioEncoding)(0),        // 0: voice_agent.InputAudio.AudioEncoding
	(OutputAudio_OutputAudioEncoding)(0), // 1: voice_agent.OutputAudio.OutputAudioEncoding
	(*InputAudio)(nil),                   // 2: voice_agent.InputAudio
	(*OutputAudio)(nil),                  // 3: voice_agent.OutputAudio
	(*Interaction)(nil),                  // 4: voice_agent.Interaction
}
var file_voiceAgent_proto_messages_proto_depIdxs = []int32{
	0, // 0: voice_agent.InputAudio.encoding:type_name -> voice_agent.InputAudio.AudioEncoding
	1, // 1: voice_agent.OutputAudio.encoding:type_name -> voice_agent.OutputAudio.OutputAudioEncoding
	2, // 2: voice_agent.Interaction.input:type_name -> voice_agent.InputAudio
	3, // 3: voice_agent.Interaction.output:type_name -> voice_agent.OutputAudio
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_voiceAgent_proto_messages_proto_init() }
func file_voiceAgent_proto_messages_proto_init() {
	if File_voiceAgent_proto_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_voiceAgent_proto_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputAudio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voiceAgent_proto_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutputAudio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voiceAgent_proto_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Interaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_voiceAgent_proto_messages_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Interaction_Input)(nil),
		(*Interaction_Output)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_voiceAgent_proto_messages_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_voiceAgent_proto_messages_proto_goTypes,
		DependencyIndexes: file_voiceAgent_proto_messages_proto_depIdxs,
		EnumInfos:         file_voiceAgent_proto_messages_proto_enumTypes,
		MessageInfos:      file_voiceAgent_proto_messages_proto_msgTypes,
	}.Build()
	File_voiceAgent_proto_messages_proto = out.File
	file_voiceAgent_proto_messages_proto_rawDesc = nil
	file_voiceAgent_proto_messages_proto_goTypes = nil
	file_voiceAgent_proto_messages_proto_depIdxs = nil
}
