// @generated by protoc-gen-es v2.2.5 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file canbiocin/proto/container.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Packaging } from "./other_pb.js";

/**
 * Describes the file canbiocin/proto/container.proto.
 */
export declare const file_canbiocin_proto_container: GenFile;

/**
 * @generated from message ShippingOption
 */
export declare type ShippingOption = Message<"ShippingOption"> & {
  /**
   * @generated from field: string shipping_id = 1;
   */
  shippingId: string;

  /**
   * @generated from field: int32 num_containers = 2;
   */
  numContainers: number;
};

/**
 * Describes the message ShippingOption.
 * Use `create(ShippingOptionSchema)` to create a new message.
 */
export declare const ShippingOptionSchema: GenMessage<ShippingOption>;

/**
 * @generated from message Container
 */
export declare type Container = Message<"Container"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: Packaging packaging = 2;
   */
  packaging?: Packaging;

  /**
   * @generated from field: int32 size_g = 3;
   */
  sizeG: number;

  /**
   * @generated from field: repeated ShippingOption shipping_options = 4;
   */
  shippingOptions: ShippingOption[];
};

/**
 * Describes the message Container.
 * Use `create(ContainerSchema)` to create a new message.
 */
export declare const ContainerSchema: GenMessage<Container>;

