// @generated by protoc-gen-es v2.2.5 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file canbiocin/proto/container.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Money } from "./money_pb.js";
import type { Supplier } from "./supplier_pb.js";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file canbiocin/proto/container.proto.
 */
export declare const file_canbiocin_proto_container: GenFile;

/**
 * @generated from message Container
 */
export declare type Container = Message<"Container"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: int32 size_g = 3;
   */
  sizeG: number;

  /**
   * @generated from field: Money unit_cost = 4;
   */
  unitCost?: Money;

  /**
   * @generated from field: Money unit_cost_shipping = 5;
   */
  unitCostShipping?: Money;

  /**
   * @generated from field: Supplier supplier = 6;
   */
  supplier?: Supplier;

  /**
   * @generated from field: google.protobuf.Timestamp most_recent_quote_date = 7;
   */
  mostRecentQuoteDate?: Timestamp;

  /**
   * @generated from field: int32 markup_percent = 9;
   */
  markupPercent: number;

  /**
   * @generated from field: string notes = 10;
   */
  notes: string;
};

/**
 * Describes the message Container.
 * Use `create(ContainerSchema)` to create a new message.
 */
export declare const ContainerSchema: GenMessage<Container>;

