// @generated by protoc-gen-es v2.2.5 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file canbiocin/proto/money.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file canbiocin/proto/money.proto.
 */
export declare const file_canbiocin_proto_money: GenFile;

/**
 * @generated from message Money
 */
export declare type Money = Message<"Money"> & {
  /**
   * @generated from field: string currency_code = 1;
   */
  currencyCode: string;

  /**
   * @generated from field: int64 units = 2;
   */
  units: bigint;

  /**
   * @generated from field: int32 nanos = 3;
   */
  nanos: number;
};

/**
 * Describes the message Money.
 * Use `create(MoneySchema)` to create a new message.
 */
export declare const MoneySchema: GenMessage<Money>;

