// @generated by protoc-gen-es v2.2.5 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file canbiocin/proto/other.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Money } from "./money_pb.js";
import type { Supplier } from "./supplier_pb.js";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file canbiocin/proto/other.proto.
 */
export declare const file_canbiocin_proto_other: GenFile;

/**
 * @generated from message Packaging
 */
export declare type Packaging = Message<"Packaging"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: Money total_cost = 3;
   */
  totalCost?: Money;

  /**
   * @generated from field: int32 units_package = 4;
   */
  unitsPackage: number;

  /**
   * @generated from field: Supplier supplier = 5;
   */
  supplier?: Supplier;

  /**
   * @generated from field: google.protobuf.Timestamp most_recent_quote_date = 6;
   */
  mostRecentQuoteDate?: Timestamp;

  /**
   * @generated from field: int32 amount_needed_for_order = 7;
   */
  amountNeededForOrder: number;

  /**
   * @generated from field: int32 markup_percent = 8;
   */
  markupPercent: number;

  /**
   * @generated from field: string notes = 9;
   */
  notes: string;
};

/**
 * Describes the message Packaging.
 * Use `create(PackagingSchema)` to create a new message.
 */
export declare const PackagingSchema: GenMessage<Packaging>;

/**
 * @generated from message Milling_Blending_Packaging
 */
export declare type Milling_Blending_Packaging = Message<"Milling_Blending_Packaging"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: Money cost_package = 3;
   */
  costPackage?: Money;

  /**
   * @generated from field: int32 num_kg = 7;
   */
  numKg: number;

  /**
   * @generated from field: Supplier supplier = 4;
   */
  supplier?: Supplier;

  /**
   * @generated from field: google.protobuf.Timestamp most_recent_quote_date = 5;
   */
  mostRecentQuoteDate?: Timestamp;

  /**
   * @generated from field: int32 markup_percent = 6;
   */
  markupPercent: number;
};

/**
 * Describes the message Milling_Blending_Packaging.
 * Use `create(Milling_Blending_PackagingSchema)` to create a new message.
 */
export declare const Milling_Blending_PackagingSchema: GenMessage<Milling_Blending_Packaging>;

