// @generated by protoc-gen-es v2.2.5 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file canbiocin/proto/postbiotics.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Money } from "./money_pb.js";
import type { Supplier } from "./supplier_pb.js";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file canbiocin/proto/postbiotics.proto.
 */
export declare const file_canbiocin_proto_postbiotics: GenFile;

/**
 * @generated from message Postbiotic
 */
export declare type Postbiotic = Message<"Postbiotic"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: int32 bag_size_kg = 3;
   */
  bagSizeKg: number;

  /**
   * @generated from field: Money cost_kg = 4;
   */
  costKg?: Money;

  /**
   * @generated from field: Money cost_shipping_kg = 5;
   */
  costShippingKg?: Money;

  /**
   * @generated from field: Supplier supplier = 6;
   */
  supplier?: Supplier;

  /**
   * @generated from field: google.protobuf.Timestamp most_recent_quote_date = 7;
   */
  mostRecentQuoteDate?: Timestamp;

  /**
   * @generated from field: string function = 9;
   */
  function: string;

  /**
   * @generated from field: string notes = 10;
   */
  notes: string;
};

/**
 * Describes the message Postbiotic.
 * Use `create(PostbioticSchema)` to create a new message.
 */
export declare const PostbioticSchema: GenMessage<Postbiotic>;

