// @generated by protoc-gen-es v2.2.5 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file canbiocin/proto/probiotics.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Money } from "./money_pb.js";
import type { Supplier } from "./supplier_pb.js";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file canbiocin/proto/probiotics.proto.
 */
export declare const file_canbiocin_proto_probiotics: GenFile;

/**
 * @generated from message Probiotic
 */
export declare type Probiotic = Message<"Probiotic"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string spp = 2;
   */
  spp: string;

  /**
   * @generated from field: string strain = 3;
   */
  strain: string;

  /**
   * @generated from field: double stock_b_cfu_g = 9;
   */
  stockBCfuG: number;

  /**
   * @generated from field: Money cost_kg = 5;
   */
  costKg?: Money;

  /**
   * @generated from field: Money cost_shipping_kg = 6;
   */
  costShippingKg?: Money;

  /**
   * @generated from field: Supplier supplier = 7;
   */
  supplier?: Supplier;

  /**
   * @generated from field: google.protobuf.Timestamp most_recent_quote_date = 8;
   */
  mostRecentQuoteDate?: Timestamp;
};

/**
 * Describes the message Probiotic.
 * Use `create(ProbioticSchema)` to create a new message.
 */
export declare const ProbioticSchema: GenMessage<Probiotic>;

