// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.1
// source: canbiocin/proto/recipe.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProbioticIngredient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item string `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	CfuG int32  `protobuf:"varint,2,opt,name=cfu_g,json=cfuG,proto3" json:"cfu_g,omitempty"`
}

func (x *ProbioticIngredient) Reset() {
	*x = ProbioticIngredient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canbiocin_proto_recipe_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbioticIngredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbioticIngredient) ProtoMessage() {}

func (x *ProbioticIngredient) ProtoReflect() protoreflect.Message {
	mi := &file_canbiocin_proto_recipe_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbioticIngredient.ProtoReflect.Descriptor instead.
func (*ProbioticIngredient) Descriptor() ([]byte, []int) {
	return file_canbiocin_proto_recipe_proto_rawDescGZIP(), []int{0}
}

func (x *ProbioticIngredient) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *ProbioticIngredient) GetCfuG() int32 {
	if x != nil {
		return x.CfuG
	}
	return 0
}

type PrebioticIngredient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item      string  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	MgServing float32 `protobuf:"fixed32,2,opt,name=mg_serving,json=mgServing,proto3" json:"mg_serving,omitempty"`
}

func (x *PrebioticIngredient) Reset() {
	*x = PrebioticIngredient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canbiocin_proto_recipe_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrebioticIngredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrebioticIngredient) ProtoMessage() {}

func (x *PrebioticIngredient) ProtoReflect() protoreflect.Message {
	mi := &file_canbiocin_proto_recipe_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrebioticIngredient.ProtoReflect.Descriptor instead.
func (*PrebioticIngredient) Descriptor() ([]byte, []int) {
	return file_canbiocin_proto_recipe_proto_rawDescGZIP(), []int{1}
}

func (x *PrebioticIngredient) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *PrebioticIngredient) GetMgServing() float32 {
	if x != nil {
		return x.MgServing
	}
	return 0
}

type PostbioticIngredient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item      string  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	MgServing float32 `protobuf:"fixed32,2,opt,name=mg_serving,json=mgServing,proto3" json:"mg_serving,omitempty"`
}

func (x *PostbioticIngredient) Reset() {
	*x = PostbioticIngredient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canbiocin_proto_recipe_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostbioticIngredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostbioticIngredient) ProtoMessage() {}

func (x *PostbioticIngredient) ProtoReflect() protoreflect.Message {
	mi := &file_canbiocin_proto_recipe_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostbioticIngredient.ProtoReflect.Descriptor instead.
func (*PostbioticIngredient) Descriptor() ([]byte, []int) {
	return file_canbiocin_proto_recipe_proto_rawDescGZIP(), []int{2}
}

func (x *PostbioticIngredient) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *PostbioticIngredient) GetMgServing() float32 {
	if x != nil {
		return x.MgServing
	}
	return 0
}

type PackagingIngredient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item       string `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	CountPerKg int32  `protobuf:"varint,2,opt,name=count_per_kg,json=countPerKg,proto3" json:"count_per_kg,omitempty"`
}

func (x *PackagingIngredient) Reset() {
	*x = PackagingIngredient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canbiocin_proto_recipe_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackagingIngredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackagingIngredient) ProtoMessage() {}

func (x *PackagingIngredient) ProtoReflect() protoreflect.Message {
	mi := &file_canbiocin_proto_recipe_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackagingIngredient.ProtoReflect.Descriptor instead.
func (*PackagingIngredient) Descriptor() ([]byte, []int) {
	return file_canbiocin_proto_recipe_proto_rawDescGZIP(), []int{3}
}

func (x *PackagingIngredient) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *PackagingIngredient) GetCountPerKg() int32 {
	if x != nil {
		return x.CountPerKg
	}
	return 0
}

type MillingIngredient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item       string `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	CountPerKg int32  `protobuf:"varint,2,opt,name=count_per_kg,json=countPerKg,proto3" json:"count_per_kg,omitempty"`
}

func (x *MillingIngredient) Reset() {
	*x = MillingIngredient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canbiocin_proto_recipe_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MillingIngredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MillingIngredient) ProtoMessage() {}

func (x *MillingIngredient) ProtoReflect() protoreflect.Message {
	mi := &file_canbiocin_proto_recipe_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MillingIngredient.ProtoReflect.Descriptor instead.
func (*MillingIngredient) Descriptor() ([]byte, []int) {
	return file_canbiocin_proto_recipe_proto_rawDescGZIP(), []int{4}
}

func (x *MillingIngredient) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *MillingIngredient) GetCountPerKg() int32 {
	if x != nil {
		return x.CountPerKg
	}
	return 0
}

type Company struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Company) Reset() {
	*x = Company{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canbiocin_proto_recipe_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_canbiocin_proto_recipe_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_canbiocin_proto_recipe_proto_rawDescGZIP(), []int{5}
}

func (x *Company) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Recipe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                      string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                    string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Company                 *Company                `protobuf:"bytes,7,opt,name=company,proto3" json:"company,omitempty"`
	Probiotics              []*ProbioticIngredient  `protobuf:"bytes,3,rep,name=probiotics,proto3" json:"probiotics,omitempty"`
	Prebiotics              []*PrebioticIngredient  `protobuf:"bytes,4,rep,name=prebiotics,proto3" json:"prebiotics,omitempty"`
	Postbiotics             []*PostbioticIngredient `protobuf:"bytes,5,rep,name=postbiotics,proto3" json:"postbiotics,omitempty"`
	ProbioticOveragePercent int32                   `protobuf:"varint,6,opt,name=probiotic_overage_percent,json=probioticOveragePercent,proto3" json:"probiotic_overage_percent,omitempty"`
}

func (x *Recipe) Reset() {
	*x = Recipe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canbiocin_proto_recipe_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Recipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipe) ProtoMessage() {}

func (x *Recipe) ProtoReflect() protoreflect.Message {
	mi := &file_canbiocin_proto_recipe_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipe.ProtoReflect.Descriptor instead.
func (*Recipe) Descriptor() ([]byte, []int) {
	return file_canbiocin_proto_recipe_proto_rawDescGZIP(), []int{6}
}

func (x *Recipe) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Recipe) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Recipe) GetCompany() *Company {
	if x != nil {
		return x.Company
	}
	return nil
}

func (x *Recipe) GetProbiotics() []*ProbioticIngredient {
	if x != nil {
		return x.Probiotics
	}
	return nil
}

func (x *Recipe) GetPrebiotics() []*PrebioticIngredient {
	if x != nil {
		return x.Prebiotics
	}
	return nil
}

func (x *Recipe) GetPostbiotics() []*PostbioticIngredient {
	if x != nil {
		return x.Postbiotics
	}
	return nil
}

func (x *Recipe) GetProbioticOveragePercent() int32 {
	if x != nil {
		return x.ProbioticOveragePercent
	}
	return 0
}

type PackagingAndMilling struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Recipe    *Recipe                `protobuf:"bytes,2,opt,name=recipe,proto3" json:"recipe,omitempty"`
	Packaging []*PackagingIngredient `protobuf:"bytes,3,rep,name=packaging,proto3" json:"packaging,omitempty"`
	Milling   []*MillingIngredient   `protobuf:"bytes,4,rep,name=milling,proto3" json:"milling,omitempty"`
}

func (x *PackagingAndMilling) Reset() {
	*x = PackagingAndMilling{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canbiocin_proto_recipe_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackagingAndMilling) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackagingAndMilling) ProtoMessage() {}

func (x *PackagingAndMilling) ProtoReflect() protoreflect.Message {
	mi := &file_canbiocin_proto_recipe_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackagingAndMilling.ProtoReflect.Descriptor instead.
func (*PackagingAndMilling) Descriptor() ([]byte, []int) {
	return file_canbiocin_proto_recipe_proto_rawDescGZIP(), []int{7}
}

func (x *PackagingAndMilling) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PackagingAndMilling) GetRecipe() *Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

func (x *PackagingAndMilling) GetPackaging() []*PackagingIngredient {
	if x != nil {
		return x.Packaging
	}
	return nil
}

func (x *PackagingAndMilling) GetMilling() []*MillingIngredient {
	if x != nil {
		return x.Milling
	}
	return nil
}

type RecipeDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipe           *Recipe              `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	ServingSizeGrams int32                `protobuf:"varint,2,opt,name=serving_size_grams,json=servingSizeGrams,proto3" json:"serving_size_grams,omitempty"`
	TotalGrams       int32                `protobuf:"varint,3,opt,name=total_grams,json=totalGrams,proto3" json:"total_grams,omitempty"`
	Ingredients      []*IngredientDetails `protobuf:"bytes,4,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
}

func (x *RecipeDetails) Reset() {
	*x = RecipeDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canbiocin_proto_recipe_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecipeDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeDetails) ProtoMessage() {}

func (x *RecipeDetails) ProtoReflect() protoreflect.Message {
	mi := &file_canbiocin_proto_recipe_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeDetails.ProtoReflect.Descriptor instead.
func (*RecipeDetails) Descriptor() ([]byte, []int) {
	return file_canbiocin_proto_recipe_proto_rawDescGZIP(), []int{8}
}

func (x *RecipeDetails) GetRecipe() *Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

func (x *RecipeDetails) GetServingSizeGrams() int32 {
	if x != nil {
		return x.ServingSizeGrams
	}
	return 0
}

func (x *RecipeDetails) GetTotalGrams() int32 {
	if x != nil {
		return x.TotalGrams
	}
	return 0
}

func (x *RecipeDetails) GetIngredients() []*IngredientDetails {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

type Ingredient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Item:
	//
	//	*Ingredient_Probiotic
	//	*Ingredient_Prebiotic
	//	*Ingredient_Postbiotic
	Item isIngredient_Item `protobuf_oneof:"item"`
}

func (x *Ingredient) Reset() {
	*x = Ingredient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canbiocin_proto_recipe_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ingredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ingredient) ProtoMessage() {}

func (x *Ingredient) ProtoReflect() protoreflect.Message {
	mi := &file_canbiocin_proto_recipe_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ingredient.ProtoReflect.Descriptor instead.
func (*Ingredient) Descriptor() ([]byte, []int) {
	return file_canbiocin_proto_recipe_proto_rawDescGZIP(), []int{9}
}

func (m *Ingredient) GetItem() isIngredient_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (x *Ingredient) GetProbiotic() *Probiotic {
	if x, ok := x.GetItem().(*Ingredient_Probiotic); ok {
		return x.Probiotic
	}
	return nil
}

func (x *Ingredient) GetPrebiotic() *Prebiotic {
	if x, ok := x.GetItem().(*Ingredient_Prebiotic); ok {
		return x.Prebiotic
	}
	return nil
}

func (x *Ingredient) GetPostbiotic() *Postbiotic {
	if x, ok := x.GetItem().(*Ingredient_Postbiotic); ok {
		return x.Postbiotic
	}
	return nil
}

type isIngredient_Item interface {
	isIngredient_Item()
}

type Ingredient_Probiotic struct {
	Probiotic *Probiotic `protobuf:"bytes,1,opt,name=probiotic,proto3,oneof"`
}

type Ingredient_Prebiotic struct {
	Prebiotic *Prebiotic `protobuf:"bytes,2,opt,name=prebiotic,proto3,oneof"`
}

type Ingredient_Postbiotic struct {
	Postbiotic *Postbiotic `protobuf:"bytes,3,opt,name=postbiotic,proto3,oneof"`
}

func (*Ingredient_Probiotic) isIngredient_Item() {}

func (*Ingredient_Prebiotic) isIngredient_Item() {}

func (*Ingredient_Postbiotic) isIngredient_Item() {}

type IngredientDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ingredient         *Ingredient `protobuf:"bytes,1,opt,name=ingredient,proto3" json:"ingredient,omitempty"`
	DesiredCfuG        int32       `protobuf:"varint,9,opt,name=desired_cfu_g,json=desiredCfuG,proto3" json:"desired_cfu_g,omitempty"`
	Percent            float64     `protobuf:"fixed64,2,opt,name=percent,proto3" json:"percent,omitempty"`
	PerservingMg       float64     `protobuf:"fixed64,3,opt,name=perserving_mg,json=perservingMg,proto3" json:"perserving_mg,omitempty"`
	TotalGrams         float64     `protobuf:"fixed64,4,opt,name=total_grams,json=totalGrams,proto3" json:"total_grams,omitempty"`
	CbCostKg           *Money      `protobuf:"bytes,5,opt,name=cb_cost_kg,json=cbCostKg,proto3" json:"cb_cost_kg,omitempty"`
	CbCostPerContainer *Money      `protobuf:"bytes,6,opt,name=cb_cost_per_container,json=cbCostPerContainer,proto3" json:"cb_cost_per_container,omitempty"`
	CbTotal            *Money      `protobuf:"bytes,7,opt,name=cb_total,json=cbTotal,proto3" json:"cb_total,omitempty"`
	ClientTotal        *Money      `protobuf:"bytes,8,opt,name=client_total,json=clientTotal,proto3" json:"client_total,omitempty"`
}

func (x *IngredientDetails) Reset() {
	*x = IngredientDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canbiocin_proto_recipe_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IngredientDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngredientDetails) ProtoMessage() {}

func (x *IngredientDetails) ProtoReflect() protoreflect.Message {
	mi := &file_canbiocin_proto_recipe_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngredientDetails.ProtoReflect.Descriptor instead.
func (*IngredientDetails) Descriptor() ([]byte, []int) {
	return file_canbiocin_proto_recipe_proto_rawDescGZIP(), []int{10}
}

func (x *IngredientDetails) GetIngredient() *Ingredient {
	if x != nil {
		return x.Ingredient
	}
	return nil
}

func (x *IngredientDetails) GetDesiredCfuG() int32 {
	if x != nil {
		return x.DesiredCfuG
	}
	return 0
}

func (x *IngredientDetails) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *IngredientDetails) GetPerservingMg() float64 {
	if x != nil {
		return x.PerservingMg
	}
	return 0
}

func (x *IngredientDetails) GetTotalGrams() float64 {
	if x != nil {
		return x.TotalGrams
	}
	return 0
}

func (x *IngredientDetails) GetCbCostKg() *Money {
	if x != nil {
		return x.CbCostKg
	}
	return nil
}

func (x *IngredientDetails) GetCbCostPerContainer() *Money {
	if x != nil {
		return x.CbCostPerContainer
	}
	return nil
}

func (x *IngredientDetails) GetCbTotal() *Money {
	if x != nil {
		return x.CbTotal
	}
	return nil
}

func (x *IngredientDetails) GetClientTotal() *Money {
	if x != nil {
		return x.ClientTotal
	}
	return nil
}

var File_canbiocin_proto_recipe_proto protoreflect.FileDescriptor

var file_canbiocin_proto_recipe_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x63, 0x61, 0x6e, 0x62, 0x69, 0x6f, 0x63, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b,
	0x63, 0x61, 0x6e, 0x62, 0x69, 0x6f, 0x63, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x63, 0x61, 0x6e,
	0x62, 0x69, 0x6f, 0x63, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x65,
	0x62, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x63,
	0x61, 0x6e, 0x62, 0x69, 0x6f, 0x63, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x72, 0x6f, 0x62, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x21, 0x63, 0x61, 0x6e, 0x62, 0x69, 0x6f, 0x63, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x6f, 0x73, 0x74, 0x62, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x62, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x49,
	0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x74, 0x65,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x13, 0x0a,
	0x05, 0x63, 0x66, 0x75, 0x5f, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x66,
	0x75, 0x47, 0x22, 0x48, 0x0a, 0x13, 0x50, 0x72, 0x65, 0x62, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x49,
	0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x74, 0x65,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x1d, 0x0a,
	0x0a, 0x6d, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x09, 0x6d, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x22, 0x49, 0x0a, 0x14,
	0x50, 0x6f, 0x73, 0x74, 0x62, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x64,
	0x69, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x67, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6d, 0x67,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x22, 0x4b, 0x0a, 0x13, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x74,
	0x65, 0x6d, 0x12, 0x20, 0x0a, 0x0c, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x70, 0x65, 0x72, 0x5f,
	0x6b, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50,
	0x65, 0x72, 0x4b, 0x67, 0x22, 0x49, 0x0a, 0x11, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x49,
	0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x74, 0x65,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x20, 0x0a,
	0x0c, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x6b, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x65, 0x72, 0x4b, 0x67, 0x22,
	0x1d, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xb1,
	0x02, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x12, 0x34, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x62, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x69, 0x6f, 0x74, 0x69,
	0x63, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x70, 0x72, 0x6f,
	0x62, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x12, 0x34, 0x0a, 0x0a, 0x70, 0x72, 0x65, 0x62, 0x69,
	0x6f, 0x74, 0x69, 0x63, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x50, 0x72,
	0x65, 0x62, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e,
	0x74, 0x52, 0x0a, 0x70, 0x72, 0x65, 0x62, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x12, 0x37, 0x0a,
	0x0b, 0x70, 0x6f, 0x73, 0x74, 0x62, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x62, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x49,
	0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x70, 0x6f, 0x73, 0x74, 0x62,
	0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x12, 0x3a, 0x0a, 0x19, 0x70, 0x72, 0x6f, 0x62, 0x69, 0x6f,
	0x74, 0x69, 0x63, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x63,
	0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x17, 0x70, 0x72, 0x6f, 0x62, 0x69,
	0x6f, 0x74, 0x69, 0x63, 0x4f, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65,
	0x6e, 0x74, 0x22, 0xa8, 0x01, 0x0a, 0x13, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x69, 0x6e, 0x67,
	0x41, 0x6e, 0x64, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65,
	0x63, 0x69, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x63,
	0x69, 0x70, 0x65, 0x52, 0x06, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x70,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x64,
	0x69, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x12,
	0x2c, 0x0a, 0x07, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x64,
	0x69, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x22, 0xb5, 0x01,
	0x0a, 0x0d, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12,
	0x1f, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x07, 0x2e, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x06, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65,
	0x12, 0x2c, 0x0a, 0x12, 0x73, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x5f, 0x67, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x6e, 0x67, 0x53, 0x69, 0x7a, 0x65, 0x47, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x67, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x47, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x34, 0x0a, 0x0b, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e,
	0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x0b, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x64,
	0x69, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x9b, 0x01, 0x0a, 0x0a, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x64,
	0x69, 0x65, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x62, 0x69, 0x6f, 0x74, 0x69,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x69, 0x6f,
	0x74, 0x69, 0x63, 0x48, 0x00, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x62, 0x69, 0x6f, 0x74, 0x69, 0x63,
	0x12, 0x2a, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x62, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x72, 0x65, 0x62, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x48,
	0x00, 0x52, 0x09, 0x70, 0x72, 0x65, 0x62, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x12, 0x2d, 0x0a, 0x0a,
	0x70, 0x6f, 0x73, 0x74, 0x62, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x62, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x48, 0x00, 0x52,
	0x0a, 0x70, 0x6f, 0x73, 0x74, 0x62, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x42, 0x06, 0x0a, 0x04, 0x69,
	0x74, 0x65, 0x6d, 0x22, 0xf3, 0x02, 0x0a, 0x11, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65,
	0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x2b, 0x0a, 0x0a, 0x69, 0x6e, 0x67,
	0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x49, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x69, 0x6e, 0x67, 0x72,
	0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x64, 0x65, 0x73, 0x69, 0x72, 0x65,
	0x64, 0x5f, 0x63, 0x66, 0x75, 0x5f, 0x67, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x43, 0x66, 0x75, 0x47, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65,
	0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x70, 0x65, 0x72,
	0x63, 0x65, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x6e, 0x67, 0x5f, 0x6d, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x70, 0x65, 0x72,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x4d, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x5f, 0x67, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x47, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x24, 0x0a, 0x0a, 0x63, 0x62,
	0x5f, 0x63, 0x6f, 0x73, 0x74, 0x5f, 0x6b, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06,
	0x2e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x08, 0x63, 0x62, 0x43, 0x6f, 0x73, 0x74, 0x4b, 0x67,
	0x12, 0x39, 0x0a, 0x15, 0x63, 0x62, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x65, 0x72, 0x5f,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x06, 0x2e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x12, 0x63, 0x62, 0x43, 0x6f, 0x73, 0x74, 0x50,
	0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x08, 0x63,
	0x62, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e,
	0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x07, 0x63, 0x62, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x29,
	0x0a, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x0b, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x1c, 0x5a, 0x1a, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x61, 0x6e, 0x62, 0x69, 0x6f, 0x63, 0x69,
	0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_canbiocin_proto_recipe_proto_rawDescOnce sync.Once
	file_canbiocin_proto_recipe_proto_rawDescData = file_canbiocin_proto_recipe_proto_rawDesc
)

func file_canbiocin_proto_recipe_proto_rawDescGZIP() []byte {
	file_canbiocin_proto_recipe_proto_rawDescOnce.Do(func() {
		file_canbiocin_proto_recipe_proto_rawDescData = protoimpl.X.CompressGZIP(file_canbiocin_proto_recipe_proto_rawDescData)
	})
	return file_canbiocin_proto_recipe_proto_rawDescData
}

var file_canbiocin_proto_recipe_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_canbiocin_proto_recipe_proto_goTypes = []interface{}{
	(*ProbioticIngredient)(nil),  // 0: ProbioticIngredient
	(*PrebioticIngredient)(nil),  // 1: PrebioticIngredient
	(*PostbioticIngredient)(nil), // 2: PostbioticIngredient
	(*PackagingIngredient)(nil),  // 3: PackagingIngredient
	(*MillingIngredient)(nil),    // 4: MillingIngredient
	(*Company)(nil),              // 5: Company
	(*Recipe)(nil),               // 6: Recipe
	(*PackagingAndMilling)(nil),  // 7: PackagingAndMilling
	(*RecipeDetails)(nil),        // 8: RecipeDetails
	(*Ingredient)(nil),           // 9: Ingredient
	(*IngredientDetails)(nil),    // 10: IngredientDetails
	(*Probiotic)(nil),            // 11: Probiotic
	(*Prebiotic)(nil),            // 12: Prebiotic
	(*Postbiotic)(nil),           // 13: Postbiotic
	(*Money)(nil),                // 14: Money
}
var file_canbiocin_proto_recipe_proto_depIdxs = []int32{
	5,  // 0: Recipe.company:type_name -> Company
	0,  // 1: Recipe.probiotics:type_name -> ProbioticIngredient
	1,  // 2: Recipe.prebiotics:type_name -> PrebioticIngredient
	2,  // 3: Recipe.postbiotics:type_name -> PostbioticIngredient
	6,  // 4: PackagingAndMilling.recipe:type_name -> Recipe
	3,  // 5: PackagingAndMilling.packaging:type_name -> PackagingIngredient
	4,  // 6: PackagingAndMilling.milling:type_name -> MillingIngredient
	6,  // 7: RecipeDetails.recipe:type_name -> Recipe
	10, // 8: RecipeDetails.ingredients:type_name -> IngredientDetails
	11, // 9: Ingredient.probiotic:type_name -> Probiotic
	12, // 10: Ingredient.prebiotic:type_name -> Prebiotic
	13, // 11: Ingredient.postbiotic:type_name -> Postbiotic
	9,  // 12: IngredientDetails.ingredient:type_name -> Ingredient
	14, // 13: IngredientDetails.cb_cost_kg:type_name -> Money
	14, // 14: IngredientDetails.cb_cost_per_container:type_name -> Money
	14, // 15: IngredientDetails.cb_total:type_name -> Money
	14, // 16: IngredientDetails.client_total:type_name -> Money
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_canbiocin_proto_recipe_proto_init() }
func file_canbiocin_proto_recipe_proto_init() {
	if File_canbiocin_proto_recipe_proto != nil {
		return
	}
	file_canbiocin_proto_money_proto_init()
	file_canbiocin_proto_prebiotics_proto_init()
	file_canbiocin_proto_probiotics_proto_init()
	file_canbiocin_proto_postbiotics_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_canbiocin_proto_recipe_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbioticIngredient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_canbiocin_proto_recipe_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrebioticIngredient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_canbiocin_proto_recipe_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostbioticIngredient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_canbiocin_proto_recipe_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackagingIngredient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_canbiocin_proto_recipe_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MillingIngredient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_canbiocin_proto_recipe_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Company); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_canbiocin_proto_recipe_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Recipe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_canbiocin_proto_recipe_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackagingAndMilling); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_canbiocin_proto_recipe_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecipeDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_canbiocin_proto_recipe_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ingredient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_canbiocin_proto_recipe_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IngredientDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_canbiocin_proto_recipe_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*Ingredient_Probiotic)(nil),
		(*Ingredient_Prebiotic)(nil),
		(*Ingredient_Postbiotic)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_canbiocin_proto_recipe_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_canbiocin_proto_recipe_proto_goTypes,
		DependencyIndexes: file_canbiocin_proto_recipe_proto_depIdxs,
		MessageInfos:      file_canbiocin_proto_recipe_proto_msgTypes,
	}.Build()
	File_canbiocin_proto_recipe_proto = out.File
	file_canbiocin_proto_recipe_proto_rawDesc = nil
	file_canbiocin_proto_recipe_proto_goTypes = nil
	file_canbiocin_proto_recipe_proto_depIdxs = nil
}
