// @generated by protoc-gen-connect-es v1.6.1 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file canbiocin/proto/service.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CalculateRecipeRequest, CalculateRecipeResponse, CreateContainerRequest, CreateContainerResponse, CreateIngredientRequest, CreateIngredientResponse, CreatePackagingRequest, CreatePackagingResponse, CreateRecipeRequest, CreateRecipeResponse, CreateSavedRecipeRequest, CreateSavedRecipeResponse, DeleteContainerRequest, DeleteContainerResponse, DeleteIngredientRequest, DeleteIngredientResponse, DeletePackagingRequest, DeletePackagingResponse, DeleteRecipeRequest, DeleteRecipeResponse, DeleteSavedRecipeRequest, DeleteSavedRecipeResponse, GetIngredientRequest, GetIngredientResponse, GetRecipeRequest, GetRecipeResponse, GetSavedRecipeRequest, GetSavedRecipeResponse, ListContainersRequest, ListContainersResponse, ListIngredientsRequest, ListIngredientsResponse, ListPackagingRequest, ListPackagingResponse, ListPrebioticCategoryRequest, ListPrebioticCategoryResponse, ListProbioticSppRequest, ListProbioticSppResponse, ListRecipesRequest, ListRecipesResponse, ListSavedRecipesRequest, ListSavedRecipesResponse, UpdateContainerRequest, UpdateContainerResponse, UpdateIngredientRequest, UpdateIngredientResponse, UpdatePackagingRequest, UpdatePackagingResponse, UpdateRecipeRequest, UpdateRecipeResponse, UpdateSavedRecipeRequest, UpdateSavedRecipeResponse } from "./service_pbjs";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service CanbiocinService
 */
export declare const CanbiocinService: {
  readonly typeName: "CanbiocinService",
  readonly methods: {
    /**
     * @generated from rpc CanbiocinService.CreateIngredient
     */
    readonly createIngredient: {
      readonly name: "CreateIngredient",
      readonly I: typeof CreateIngredientRequest,
      readonly O: typeof CreateIngredientResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.GetIngredient
     */
    readonly getIngredient: {
      readonly name: "GetIngredient",
      readonly I: typeof GetIngredientRequest,
      readonly O: typeof GetIngredientResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.UpdateIngredient
     */
    readonly updateIngredient: {
      readonly name: "UpdateIngredient",
      readonly I: typeof UpdateIngredientRequest,
      readonly O: typeof UpdateIngredientResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.DeleteIngredient
     */
    readonly deleteIngredient: {
      readonly name: "DeleteIngredient",
      readonly I: typeof DeleteIngredientRequest,
      readonly O: typeof DeleteIngredientResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.ListIngredients
     */
    readonly listIngredients: {
      readonly name: "ListIngredients",
      readonly I: typeof ListIngredientsRequest,
      readonly O: typeof ListIngredientsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.ListProbioticSpp
     */
    readonly listProbioticSpp: {
      readonly name: "ListProbioticSpp",
      readonly I: typeof ListProbioticSppRequest,
      readonly O: typeof ListProbioticSppResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.ListPrebioticCategory
     */
    readonly listPrebioticCategory: {
      readonly name: "ListPrebioticCategory",
      readonly I: typeof ListPrebioticCategoryRequest,
      readonly O: typeof ListPrebioticCategoryResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.CreateRecipe
     */
    readonly createRecipe: {
      readonly name: "CreateRecipe",
      readonly I: typeof CreateRecipeRequest,
      readonly O: typeof CreateRecipeResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.GetRecipe
     */
    readonly getRecipe: {
      readonly name: "GetRecipe",
      readonly I: typeof GetRecipeRequest,
      readonly O: typeof GetRecipeResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.UpdateRecipe
     */
    readonly updateRecipe: {
      readonly name: "UpdateRecipe",
      readonly I: typeof UpdateRecipeRequest,
      readonly O: typeof UpdateRecipeResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.DeleteRecipe
     */
    readonly deleteRecipe: {
      readonly name: "DeleteRecipe",
      readonly I: typeof DeleteRecipeRequest,
      readonly O: typeof DeleteRecipeResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.ListRecipes
     */
    readonly listRecipes: {
      readonly name: "ListRecipes",
      readonly I: typeof ListRecipesRequest,
      readonly O: typeof ListRecipesResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.CalculateRecipe
     */
    readonly calculateRecipe: {
      readonly name: "CalculateRecipe",
      readonly I: typeof CalculateRecipeRequest,
      readonly O: typeof CalculateRecipeResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.CreateContainer
     */
    readonly createContainer: {
      readonly name: "CreateContainer",
      readonly I: typeof CreateContainerRequest,
      readonly O: typeof CreateContainerResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.DeleteContainer
     */
    readonly deleteContainer: {
      readonly name: "DeleteContainer",
      readonly I: typeof DeleteContainerRequest,
      readonly O: typeof DeleteContainerResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.UpdateContainer
     */
    readonly updateContainer: {
      readonly name: "UpdateContainer",
      readonly I: typeof UpdateContainerRequest,
      readonly O: typeof UpdateContainerResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.ListContainers
     */
    readonly listContainers: {
      readonly name: "ListContainers",
      readonly I: typeof ListContainersRequest,
      readonly O: typeof ListContainersResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.CreateSavedRecipe
     */
    readonly createSavedRecipe: {
      readonly name: "CreateSavedRecipe",
      readonly I: typeof CreateSavedRecipeRequest,
      readonly O: typeof CreateSavedRecipeResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.GetSavedRecipe
     */
    readonly getSavedRecipe: {
      readonly name: "GetSavedRecipe",
      readonly I: typeof GetSavedRecipeRequest,
      readonly O: typeof GetSavedRecipeResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.UpdateSavedRecipe
     */
    readonly updateSavedRecipe: {
      readonly name: "UpdateSavedRecipe",
      readonly I: typeof UpdateSavedRecipeRequest,
      readonly O: typeof UpdateSavedRecipeResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.DeleteSavedRecipe
     */
    readonly deleteSavedRecipe: {
      readonly name: "DeleteSavedRecipe",
      readonly I: typeof DeleteSavedRecipeRequest,
      readonly O: typeof DeleteSavedRecipeResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.ListSavedRecipes
     */
    readonly listSavedRecipes: {
      readonly name: "ListSavedRecipes",
      readonly I: typeof ListSavedRecipesRequest,
      readonly O: typeof ListSavedRecipesResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.CreatePackaging
     */
    readonly createPackaging: {
      readonly name: "CreatePackaging",
      readonly I: typeof CreatePackagingRequest,
      readonly O: typeof CreatePackagingResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.DeletePackaging
     */
    readonly deletePackaging: {
      readonly name: "DeletePackaging",
      readonly I: typeof DeletePackagingRequest,
      readonly O: typeof DeletePackagingResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.UpdatePackaging
     */
    readonly updatePackaging: {
      readonly name: "UpdatePackaging",
      readonly I: typeof UpdatePackagingRequest,
      readonly O: typeof UpdatePackagingResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc CanbiocinService.ListPackaging
     */
    readonly listPackaging: {
      readonly name: "ListPackaging",
      readonly I: typeof ListPackagingRequest,
      readonly O: typeof ListPackagingResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

