// @generated by protoc-gen-es v2.2.5 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file canbiocin/proto/service.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Ingredient } from "./recipe_pb.js";

/**
 * Describes the file canbiocin/proto/service.proto.
 */
export declare const file_canbiocin_proto_service: GenFile;

/**
 * @generated from message CreateIngredientRequest
 */
export declare type CreateIngredientRequest = Message<"CreateIngredientRequest"> & {
  /**
   * @generated from field: Ingredient ingredient = 1;
   */
  ingredient?: Ingredient;
};

/**
 * Describes the message CreateIngredientRequest.
 * Use `create(CreateIngredientRequestSchema)` to create a new message.
 */
export declare const CreateIngredientRequestSchema: GenMessage<CreateIngredientRequest>;

/**
 * @generated from message CreateIngredientResponse
 */
export declare type CreateIngredientResponse = Message<"CreateIngredientResponse"> & {
};

/**
 * Describes the message CreateIngredientResponse.
 * Use `create(CreateIngredientResponseSchema)` to create a new message.
 */
export declare const CreateIngredientResponseSchema: GenMessage<CreateIngredientResponse>;

/**
 * @generated from message UpdateIngredientRequest
 */
export declare type UpdateIngredientRequest = Message<"UpdateIngredientRequest"> & {
  /**
   * @generated from field: Ingredient ingredient = 1;
   */
  ingredient?: Ingredient;
};

/**
 * Describes the message UpdateIngredientRequest.
 * Use `create(UpdateIngredientRequestSchema)` to create a new message.
 */
export declare const UpdateIngredientRequestSchema: GenMessage<UpdateIngredientRequest>;

/**
 * @generated from message UpdateIngredientResponse
 */
export declare type UpdateIngredientResponse = Message<"UpdateIngredientResponse"> & {
};

/**
 * Describes the message UpdateIngredientResponse.
 * Use `create(UpdateIngredientResponseSchema)` to create a new message.
 */
export declare const UpdateIngredientResponseSchema: GenMessage<UpdateIngredientResponse>;

/**
 * @generated from message ListIngredientsRequest
 */
export declare type ListIngredientsRequest = Message<"ListIngredientsRequest"> & {
};

/**
 * Describes the message ListIngredientsRequest.
 * Use `create(ListIngredientsRequestSchema)` to create a new message.
 */
export declare const ListIngredientsRequestSchema: GenMessage<ListIngredientsRequest>;

/**
 * @generated from message ListIngredientsResponse
 */
export declare type ListIngredientsResponse = Message<"ListIngredientsResponse"> & {
  /**
   * @generated from field: repeated Ingredient ingredient = 1;
   */
  ingredient: Ingredient[];
};

/**
 * Describes the message ListIngredientsResponse.
 * Use `create(ListIngredientsResponseSchema)` to create a new message.
 */
export declare const ListIngredientsResponseSchema: GenMessage<ListIngredientsResponse>;

/**
 * @generated from message CreateRecipeRequest
 */
export declare type CreateRecipeRequest = Message<"CreateRecipeRequest"> & {
};

/**
 * Describes the message CreateRecipeRequest.
 * Use `create(CreateRecipeRequestSchema)` to create a new message.
 */
export declare const CreateRecipeRequestSchema: GenMessage<CreateRecipeRequest>;

/**
 * @generated from message CreateRecipeResponse
 */
export declare type CreateRecipeResponse = Message<"CreateRecipeResponse"> & {
};

/**
 * Describes the message CreateRecipeResponse.
 * Use `create(CreateRecipeResponseSchema)` to create a new message.
 */
export declare const CreateRecipeResponseSchema: GenMessage<CreateRecipeResponse>;

/**
 * @generated from message UpdateRecipeRequest
 */
export declare type UpdateRecipeRequest = Message<"UpdateRecipeRequest"> & {
};

/**
 * Describes the message UpdateRecipeRequest.
 * Use `create(UpdateRecipeRequestSchema)` to create a new message.
 */
export declare const UpdateRecipeRequestSchema: GenMessage<UpdateRecipeRequest>;

/**
 * @generated from message UpdateRecipeResponse
 */
export declare type UpdateRecipeResponse = Message<"UpdateRecipeResponse"> & {
};

/**
 * Describes the message UpdateRecipeResponse.
 * Use `create(UpdateRecipeResponseSchema)` to create a new message.
 */
export declare const UpdateRecipeResponseSchema: GenMessage<UpdateRecipeResponse>;

/**
 * @generated from message ListRecipesRequest
 */
export declare type ListRecipesRequest = Message<"ListRecipesRequest"> & {
};

/**
 * Describes the message ListRecipesRequest.
 * Use `create(ListRecipesRequestSchema)` to create a new message.
 */
export declare const ListRecipesRequestSchema: GenMessage<ListRecipesRequest>;

/**
 * @generated from message ListRecipesResponse
 */
export declare type ListRecipesResponse = Message<"ListRecipesResponse"> & {
};

/**
 * Describes the message ListRecipesResponse.
 * Use `create(ListRecipesResponseSchema)` to create a new message.
 */
export declare const ListRecipesResponseSchema: GenMessage<ListRecipesResponse>;

/**
 * @generated from message CalculateRecipeRequest
 */
export declare type CalculateRecipeRequest = Message<"CalculateRecipeRequest"> & {
};

/**
 * Describes the message CalculateRecipeRequest.
 * Use `create(CalculateRecipeRequestSchema)` to create a new message.
 */
export declare const CalculateRecipeRequestSchema: GenMessage<CalculateRecipeRequest>;

/**
 * @generated from message CalculateRecipeResponse
 */
export declare type CalculateRecipeResponse = Message<"CalculateRecipeResponse"> & {
};

/**
 * Describes the message CalculateRecipeResponse.
 * Use `create(CalculateRecipeResponseSchema)` to create a new message.
 */
export declare const CalculateRecipeResponseSchema: GenMessage<CalculateRecipeResponse>;

/**
 * @generated from service Canbiocin
 */
export declare const Canbiocin: GenService<{
  /**
   * @generated from rpc Canbiocin.CreateIngredient
   */
  createIngredient: {
    methodKind: "unary";
    input: typeof CreateIngredientRequestSchema;
    output: typeof CreateIngredientResponseSchema;
  },
  /**
   * @generated from rpc Canbiocin.UpdateIngredient
   */
  updateIngredient: {
    methodKind: "unary";
    input: typeof UpdateIngredientRequestSchema;
    output: typeof UpdateIngredientResponseSchema;
  },
  /**
   * @generated from rpc Canbiocin.ListIngredients
   */
  listIngredients: {
    methodKind: "unary";
    input: typeof ListIngredientsRequestSchema;
    output: typeof ListIngredientsResponseSchema;
  },
  /**
   * @generated from rpc Canbiocin.CreateRecipe
   */
  createRecipe: {
    methodKind: "unary";
    input: typeof CreateRecipeRequestSchema;
    output: typeof CreateRecipeResponseSchema;
  },
  /**
   * @generated from rpc Canbiocin.UpdateRecipe
   */
  updateRecipe: {
    methodKind: "unary";
    input: typeof UpdateRecipeRequestSchema;
    output: typeof UpdateRecipeResponseSchema;
  },
  /**
   * @generated from rpc Canbiocin.ListRecipes
   */
  listRecipes: {
    methodKind: "unary";
    input: typeof ListRecipesRequestSchema;
    output: typeof ListRecipesResponseSchema;
  },
  /**
   * @generated from rpc Canbiocin.CalculateRecipe
   */
  calculateRecipe: {
    methodKind: "unary";
    input: typeof CalculateRecipeRequestSchema;
    output: typeof CalculateRecipeResponseSchema;
  },
}>;

