// @generated by protoc-gen-connect-es v1.6.1 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file canbiocin/proto/service.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CalculateRecipeRequest, CalculateRecipeResponse, CreateIngredientRequest, CreateIngredientResponse, CreateRecipeRequest, CreateRecipeResponse, ListIngredientsRequest, ListIngredientsResponse, ListRecipesRequest, ListRecipesResponse, UpdateIngredientRequest, UpdateIngredientResponse, UpdateRecipeRequest, UpdateRecipeResponse } from "./service_pbjs";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service Canbiocin
 */
export declare const Canbiocin: {
  readonly typeName: "Canbiocin",
  readonly methods: {
    /**
     * @generated from rpc Canbiocin.CreateIngredient
     */
    readonly createIngredient: {
      readonly name: "CreateIngredient",
      readonly I: typeof CreateIngredientRequest,
      readonly O: typeof CreateIngredientResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc Canbiocin.UpdateIngredient
     */
    readonly updateIngredient: {
      readonly name: "UpdateIngredient",
      readonly I: typeof UpdateIngredientRequest,
      readonly O: typeof UpdateIngredientResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc Canbiocin.ListIngredients
     */
    readonly listIngredients: {
      readonly name: "ListIngredients",
      readonly I: typeof ListIngredientsRequest,
      readonly O: typeof ListIngredientsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc Canbiocin.CreateRecipe
     */
    readonly createRecipe: {
      readonly name: "CreateRecipe",
      readonly I: typeof CreateRecipeRequest,
      readonly O: typeof CreateRecipeResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc Canbiocin.UpdateRecipe
     */
    readonly updateRecipe: {
      readonly name: "UpdateRecipe",
      readonly I: typeof UpdateRecipeRequest,
      readonly O: typeof UpdateRecipeResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc Canbiocin.ListRecipes
     */
    readonly listRecipes: {
      readonly name: "ListRecipes",
      readonly I: typeof ListRecipesRequest,
      readonly O: typeof ListRecipesResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc Canbiocin.CalculateRecipe
     */
    readonly calculateRecipe: {
      readonly name: "CalculateRecipe",
      readonly I: typeof CalculateRecipeRequest,
      readonly O: typeof CalculateRecipeResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

