// @generated by protoc-gen-es v2.2.5 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file canbiocin/proto/supplier.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file canbiocin/proto/supplier.proto.
 */
export declare const file_canbiocin_proto_supplier: GenFile;

/**
 * @generated from message Supplier
 */
export declare type Supplier = Message<"Supplier"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string contact_name = 3;
   */
  contactName: string;

  /**
   * @generated from field: string email = 4;
   */
  email: string;

  /**
   * @generated from field: string phone = 5;
   */
  phone: string;

  /**
   * @generated from field: string address = 6;
   */
  address: string;

  /**
   * @generated from field: string website = 7;
   */
  website: string;

  /**
   * @generated from field: string notes = 8;
   */
  notes: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 9;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 10;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: bool is_active = 11;
   */
  isActive: boolean;

  /**
   * @generated from field: repeated string product_categories = 12;
   */
  productCategories: string[];

  /**
   * @generated from field: string payment_terms = 13;
   */
  paymentTerms: string;

  /**
   * @generated from field: string shipping_terms = 14;
   */
  shippingTerms: string;
};

/**
 * Describes the message Supplier.
 * Use `create(SupplierSchema)` to create a new message.
 */
export declare const SupplierSchema: GenMessage<Supplier>;

